#!/bin/bash

WIFI_ENABLED=$(nmcli radio wifi)

if [ $1 = "wifi_enabled" ]; then
  if [ $WIFI_ENABLED = "enabled" ]; then
    echo "enabled"
  else
    echo "disabled"
  fi
elif [ $1 = "wifi_off" ]; then
  nmcli radio wifi off
  eww update "wifi_enabled" "diasbled"
elif [ $1 = "wifi_on" ]; then
  nmcli radio wifi on
  eww update "wifi_enabled" "enabled"
fi

