#! /bin/bash

#define icons for workspaces 1-9
ic=(0 Term Browser Files Music Videos CS:GO Other)

#initial check for occupied workspaces
for num in $(hyprctl workspaces | grep ID | sed 's/()/(1)/g' | awk 'NR>1{print $1}' RS='(' FS=')'); do 
  export o"$num"="$num"
done
 
#initial check for focused workspace
for num in $(hyprctl monitors | grep active | sed 's/()/(1)/g' | awk 'NR>1{print $1}' RS='(' FS=')'); do 
  export f"$num"="$num"
  export fnum=f"$num"
done

workspaces() {
if [[ ${1:0:9} == "workspace" ]]; then #set focused workspace
  unset -v "$fnum"
  num=${1:11}
  export f"$num"="$num"
  export fnum=f"$num"

elif [[ ${1:0:15} == "createworkspace" ]]; then #set Occupied workspace
  num=${1:17}
  export o"$num"="$num"
  export f"$num"="$num"

elif [[ ${1:0:16} == "destroyworkspace" ]]; then #unset unoccupied workspace
  num=${1:18}
  unset -v o"$num" f"$num"
fi

content1=""
content2=""
content3=""
content4=""
content5=""
content6=""
[ "$o1" ] && content1=""
[ "$o2" ] && content2=""
[ "$o3" ] && content3=""
[ "$o4" ] && content4=""
[ "$o5" ] && content5=""
[ "$o6" ] && content6=""
[ "$f1" ] && content1=""
 [ "$f2" ] && content2=""
[ "$f3" ] && content3=""
[ "$f4" ] && content4=""
[ "$f5" ] && content5=""
[ "$f6" ] && content6=""

#output eww widget
echo 	"(box	:class \"workspaces\"	:orientation \"h\" :spacing 5 :space-evenly \"true\" 	\
              (button :onclick \"hyprctl dispatch workspace 1\" :onrightclick \"hyprctl dispatch workspace 1\" :class \"0$o1$f1\" \"$content1\") \
              (button :onclick \"hyprctl dispatch workspace 2\" :onrightclick \"hyprctl dispatch workspace 2\"	:class \"0$o2$f2\" \"$content2\") \
              (button :onclick \"hyprctl dispatch workspace 3\" :onrightclick \"hyprctl dispatch workspace 3\"	:class \"0$o3$f3\" \"$content3\") \
              (button :onclick \"hyprctl dispatch workspace 4\" :onrightclick \"hyprctl dispatch workspace 4\"	:class \"0$o4$f4\" \"$content4\") \
              (button :onclick \"hyprctl dispatch workspace 5\" :onrightclick \"hyprctl dispatch workspace 5\"	:class \"0$o5$f5\" \"$content5\") \
              (button :onclick \"hyprctl dispatch workspace 6\" :onrightclick \"hyprctl dispatch workspace 6\"	:class \"0$o6$f6\" \"$content6\") \
          )"
}

workspaces

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r event; do 
workspaces "$event"
done
