#! /bin/bash

#define icons for workspaces 1-9
ic=(0 Term Browser Files Music Videos CS:GO Other)

#initial check for occupied workspaces
for num in $(bspc query -D -d .occupied --names); do 
  export o"$num"="$num"
done
 
#initial check for focused workspace
for num in $(bspc query -D -d focused --names); do 
  export f"$num"="$num"
  export fnum=f"$num"
done

workspaces() {
if [[ ${1:0:13} == "desktop_focus" ]]; then #set focused workspace
  unset -v "$fnum"
  num=$(bspc query -D -d --names)
  export f"$num"="$num"
  export fnum=f"$num"

elif [[ ${1:0:8} == "node_add" ]]; then #set Occupied workspace
  for num in $(bspc query -D -d .occupied --names); do 
    export o"$num"="$num"
  done
  

elif [[ ${1:0:11} == "node_remove" ]]; then #unset unoccupied workspace
  for num in $(bspc query -D --names); do 
    unset -v o"$num" f"$num"
    unset -v f"$num" f"$num"
  done

  for num in $(bspc query -D -d .occupied --names); do 
    export o"$num"="$num"
  done
   
  for num in $(bspc query -D -d focused --names); do 
    export f"$num"="$num"
    export fnum=f"$num"
  done
  fi

content1=""
content2=""
content3=""
content4=""
content5=""
content6=""
[ "$o1" ] && content1=""
[ "$o2" ] && content2=""
[ "$o3" ] && content3=""
[ "$o4" ] && content4=""
[ "$o5" ] && content5=""
[ "$o6" ] && content6=""
[ "$f1" ] && content1=""
 [ "$f2" ] && content2=""
[ "$f3" ] && content3=""
[ "$f4" ] && content4=""
[ "$f5" ] && content5=""
[ "$f6" ] && content6=""

#output eww widget
echo 	"(box	:class \"workspaces\"	:orientation \"h\" :spacing 5 :space-evenly \"true\" 	\
              (button :onclick \"bspc desktop -f 1\" :onrightclick \"hyprctl dispatch workspace 1\" :class \"0$o1$f1\" \"$content1\") \
              (button :onclick \"bspc desktop -f 2\" :onrightclick \"bspc desktop -f 2\"	:class \"0$o2$f2\" \"$content2\") \
              (button :onclick \"bspc desktop -f 3\" :onrightclick \"bspc desktop -f 3\"	:class \"0$o3$f3\" \"$content3\") \
              (button :onclick \"bspc desktop -f 4\" :onrightclick \"bspc desktop -f 4\"	:class \"0$o4$f4\" \"$content4\") \
              (button :onclick \"bspc desktop -f 5\" :onrightclick \"bspc desktop -f 5\"	:class \"0$o5$f5\" \"$content5\") \
              (button :onclick \"bspc desktop -f 6\" :onrightclick \"bspc desktop -f 6\"	:class \"0$o6$f6\" \"$content6\") \
          )"
}

workspaces

bspc subscribe desktop_focus node_add node_remove 2> /dev/null | while read -r event; do 
workspaces "$event"
done
