#!/usr/bin/env bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-fill $SCRIPTPATH/down.jpg
fi

echo "UnloadTheme" > $XDG_RUNTIME_DIR/leftwm/commands.pipe


# Kill procs
pkill picom &
pkill polybar &
pkill dunst &
pkill gnome-keyring-daemon &
pkill i3-battery-popup &
pkill nm-applet &
if [ -x "$(command -v eww)" ]; then
  eww kill
fi