#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Autostart

# xss-lock with betterlockscreen for inactivity
if [ -x "$(command -v xss-lock)" ]; then
  xss-lock --transfer-sleep-lock -- betterlockscreen -l blur &
fi

if [ -x "$(command -v picom)" ]; then
  picom --experimental-backend &
fi

# Eww
if [ -x "$(command -v eww)" ]; then
  eww daemon &
  eww close bar_window
  eww open bar_window
fi

# Wallpaper
feh --bg-scale .config/wallpaper/wallpaper.jpg

bspc monitor -d 1 2 3 4 5 6 7 

bspc config border_width         2
bspc config window_gap          12
bspc config normal_border_color \#6C7086
bspc config focused_border_color \#B4BEfE 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Scratchpad terminal
bspc rule -a scratchterm state=floating rectangle="640x400+640+300" 
