#!/bin/bash

BLUETOOTH_ENABLED=$(bluetoothctl show | grep Powered | cut -c '11-')

if [ $1 = "bluetooth_enabled" ]; then
  if [ $BLUETOOTH_ENABLED = "yes" ]; then
    echo "enabled"
  else
    echo "disabled"
  fi
elif [ $1 = "bluetooth_off" ]; then
  bluetoothctl power off
  eww update "bluetooth_enabled"="diasbled"
elif [ $1 = "bluetooth_on" ]; then
  bluetoothctl power on
  eww update "bluetooth_enabled"="enabled"
fi
