#!/bin/bash

STATUS="$(playerctl -p spotify status)"

if [[ $1 == "--icon" ]]; then
    if [[ $STATUS == "Paused" ]]; then
      echo ""
    elif [[ $STATUS == "Playing" ]]; then
      echo ""
    else
      echo "/"      
    fi
elif [[ $1 == "--play" ]]; then
  playerctl -p spotify play
elif [[ $1 == "--pause" ]]; then
  playerctl -p spotify pause
elif [[ $1 == "--play-pause" ]]; then
  playerctl -p spotify play-pause
    if [[ $STATUS == "Paused" ]]; then
    eww -c $HOME/.config/leftwm/themes/current/eww-bar update playpause_icon=""
  elif [[ $STATUS == "Playing" ]]; then
    eww -c $HOME/.config/leftwm/themes/current/eww-bar update playpause_icon=""
  fi
fi
