#!/bin/sh

VPN_PROFILE="fr12-wireguard"
STATUS=$(nmcli -f GENERAL.STATE con show $VPN_PROFILE | tr -s ' ' | cut -c '16-')

if [ $1 = "vpn_enabled" ]; then
  if [ $STATUS = "activated" ]; then
    echo "enabled"
  else
    echo "disabled"
  fi
elif [ $1 = "vpn_on" ]; then
  nmcli con up $VPN_PROFILE
elif [ $1 = "vpn_off" ]; then
  nmcli con down $VPN_PROFILE
fi
