#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Autostart

# xss-lock with betterlockscreen for inactivity
if [ -x "$(command -v xss-lock)" ]; then
  xss-lock --transfer-sleep-lock -- betterlockscreen -l blur &
fi

if [ -x "$(command -v picom)" ]; then
  picom &
fi

# pkill polybar
# polybar left &
# polybar center &
# polybar right &

if [ -x "$(command -v eww)" ]; then
  eww daemon &
  eww open bar_window
fi

# Notif daemon
if [ -x "$(command -v dunst)" ]; then
  dunst &
fi
# Wallpaper
feh --bg-scale .config/wallpaper/rei-tux.png

bspc monitor -d 1 2 3 4 5 6 

bspc config border_width         3
bspc config window_gap           10
bspc config normal_border_color \#313244
bspc config focused_border_color \#cdd6f4

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Scratchpad terminal
bspc rule -a scratchterm state=floating rectangle="750x450+630+300" 

# Tiling windows
bspc rule -a Zathura state=tiled

setxkbmap -layout fr,bqn -variant oss, -option grp:alt_shift_toggle
